apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: time-based-trigger
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: time-based-trigger
  name: time-based-trigger
  namespace: time-based-trigger
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: time-based-trigger
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: time-based-trigger
    spec:
      containers:
      - image: phoenixop/time-based-trigger:0.0.1
        name: time-based-trigger
        resources: {}
        imagePullPolicy: Always
status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: time-based-trigger
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - amtd.r6security.com
  resources:
  - securityevents
  verbs:
  - get
  - list
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: time-based-trigger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: time-based-trigger
subjects:
- kind: ServiceAccount
  name: default
  namespace: time-based-trigger