apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: demo-page
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-page
  name: demo-page
  namespace: demo-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-page
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-page
    spec:
      containers:
      - image: nginx:1.25.1
        name: nginx
        resources: {}
        ports:
        - name: web-server
          containerPort: 80
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo-page
  name: demo-page
  namespace: demo-page
spec:
  ports:
  - name: web-server
    port: 80
    protocol: TCP
    targetPort: web-server
  selector:
    app: demo-page
  type: ClusterIP
status:
  loadBalancer: {}