apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: falco-integrator
spec: {}
status: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: falco-integrator
  name: falco-integrator
  namespace: falco-integrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: falco-integrator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: falco-integrator
    spec:
      containers:
      - image: phoenixop/falco-integrator:0.0.1
        name: falco-integrator
        resources: {}
        imagePullPolicy: Always
        env:
        - name: SERVER_PORT
          value: "11111"
        ports:
        - name: web
          containerPort: 11111
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: falco-integrator
  namespace: falco-integrator
spec:
  selector:
    app.kubernetes.io/name: falco-integrator
  ports:
    - protocol: TCP
      port: 80
      targetPort: web
      name: web
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: falco-integrator
rules:
- apiGroups:
  - amtd.r6security.com
  resources:
  - securityevents
  verbs:
  - get
  - list
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: falco-integrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: falco-integrator
subjects:
- kind: ServiceAccount
  name: default
  namespace: falco-integrator
